name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Get code
        uses: actions/checkout@v3  

      - name: Move code SSH
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SOURCE: "./"
          REMOTE_HOST: ${{secrets.SSH_HOST}}
          REMOTE_USER: ${{secrets.USER_NAME }}
          TARGET: "/home/ubutnu/app"
        
            
        


